version: "3.8"
services:
  neo4j:
    image: neo4j:5.23
    environment:
      - NEO4J_AUTH=neo4j/testpass
      - NEO4J_dbms_memory_heap_max__size=1g
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
volumes:
  neo4j-data:
