github_models:
  endpoint: "https://models.github.ai/inference/chat/completions"
  token: ""
  default_model: "openai/gpt-4o"
gemini:
  endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
  api_key: "
  default_model: "gemini-2.0-flash"
use_model: "gemini"  # Change to "gemini" to use Gemini API
